### ISSUE TITLE
Error: undefined identifier `inet_pton`

### ISSUE THREAD

**Issue by ptr727** [CyberShadow/dhcptest#28]
Hi, trying to troubleshoot option 119.
Added:

```
/// https://www.rfc-editor.org/rfc/rfc3397
119 : DHCPOptionSpec("Domain Search Option", OptionFormat.str),
```

Get:

```
PS C:\Users\piete\source\repos\CyberShadow\dhcptest> C:\Users\piete\Downloads\dmd.2.102.2.windows\dmd2\windows\bin64\dmd.exe dhcptest.d
dhcptest.d(1029): Error: undefined identifier `inet_pton`
PS C:\Users\piete\source\repos\CyberShadow\dhcptest> C:\Users\piete\Downloads\dmd.2.102.2.windows\dmd2\windows\bin\dmd.exe dhcptest.d
dhcptest.d(1029): Error: undefined identifier `inet_pton`
PS C:\Users\piete\source\repos\CyberShadow\dhcptest>
```

Any help on how to compile on Windows please using dmd.2.102.2.windows?
If you could create a VSCode project that would be awesome.

**Comment by CyberShadow** [comment]
This was a regression introduced in #26.

Fixed in 083f02d9ec8e73db378e793ca70822e65138adc1.
